
### without api-key
GET {{http-host}}/{{prefix}}/{{v1}}/cats HTTP/1.1

### with non-existent key
GET {{http-host}}/{{prefix}}/{{v1}}/cats HTTP/1.1
X-API-KEY: api_key

### with revoked key
GET {{http-host}}/{{prefix}}/{{v1}}/cats HTTP/1.1
X-API-KEY: $2b$10$EPC7Iq3wAjmD29hlsGKkC.XOnGAzP3khul9zR1jn2KyC.QTfbyp9W

### with valid api-key
GET {{http-host}}/{{prefix}}/{{v1}}/cats HTTP/1.1
X-API-KEY: $2b$10$EPC7Iq3wAjmD29hlsGKkC.XOnGAzP3khul9zR1jn2KyC.QTfbyp9W