
###  without api-key
GET {{http-host}}/{{prefix}}/{{v1}}/cats/CvhOrd3S_ HTTP/1.1

### with non-existent key
GET {{http-host}}/{{prefix}}/{{v1}}/cats/CvhOrd3S_ HTTP/1.1
X-API-KEY: api_key

### with revoked key
GET {{http-host}}/{{prefix}}/{{v1}}/cats/CvhOrd3S_ HTTP/1.1
X-API-KEY: $2b$10$YzIlwZ0RpiDcKdSQNSTc4uMciyLzb/J/cIJDTFclwWzV5j9JWCohO

### with valid api-key
GET {{http-host}}/{{prefix}}/{{v1}}/cats/CvhOrd3S_ HTTP/1.1
X-API-KEY: $2b$10$YzIlwZ0RpiDcKdSQNSTc4uMciyLzb/J/cIJDTFclwWzV5j9JWCohO